---
- name: Deploy Configurations to Devices Using CloudVision Portal # (1)!
  hosts: CLOUDVISION
  gather_facts: false
  tasks:
    - name: Upload cvp configlets
      ansible.builtin.import_role:
          name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'intended/structured_configs/cvp/cvp_configlets'
        file_extension: 'yml'
        configlets_cvp_prefix: 'AVD-CLAB'
        execute_tasks: false
        cv_collection: v3
    
    - name: Deploy Configurations to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'DC1-AVD-CLAB'
        state: present
        execute_tasks: false
        cv_collection: v3 
        fabric_name: FABRIC
